# Generated by Django 4.2.3 on 2023-09-24 01:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_open",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
