# Generated by Django 4.2.3 on 2023-09-24 01:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_registration_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="logistics_month",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Jan"),
                    (2, "Feb"),
                    (3, "Mar"),
                    (4, "Apr"),
                    (5, "May"),
                    (6, "Jun"),
                    (7, "Jul"),
                    (8, "Aug"),
                    (10, "Oct"),
                    (11, "Nov"),
                    (12, "Dec"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="logistics_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
