# Generated by Django 4.2.3 on 2023-09-24 02:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0004_undostackentry"),
        ("events", "0003_event_logistics_month_event_logistics_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="attended_periods",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="canceled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_registrations",
                to="character.character",
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="sheet",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.sheet",
            ),
        ),
    ]
