# Generated by Django 4.2.3 on 2023-09-24 14:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_eventregistration_attended_periods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="logistics_month",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Jan"),
                    (2, "Feb"),
                    (3, "Mar"),
                    (4, "Apr"),
                    (5, "May"),
                    (6, "Jun"),
                    (7, "Jul"),
                    (8, "Aug"),
                    (10, "Oct"),
                    (11, "Nov"),
                    (12, "Dec"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="logistics_year",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["campaign", "chapter", "logistics_year", "logistics_month"],
                name="campaign-year-month-idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(fields=["event", "user"], name="event-user-idx"),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "character"], name="event-character-idx"
            ),
        ),
    ]
