name: Sources
incant: None
call: None
target: None
delivery: None
accent: None
duration: Special
refresh: Event
effect: None
description: |
  The Socialite has access to closed markets before gatherings via business partners and associates.

  A Sources List containing prices and quantities will be available at Check-In. Basic Resources, otherwise unavailable items, information, or other curiosities and oddities Plot deems fit will rotate through this list.
