name: Sources
incant: None
call: None
target: Resources
delivery: None
accent: None
duration: Instantaneous
refresh: Event
effect: Special
description: At Check-In, the Socialite may purchase a number of items from the closed markets made available to them by business partners or associates. The Socialite can purchase any of a number of items from the Available Items List presented at Check-In. These items’ price and quantity are determined by staff, and will be dependent on current plot circumstances. The Check-In list may contain anything from basic resources, items not otherwise available in this area, information, or other curios and oddities as Plot deems fit.
