# Generated by Django 4.2.3 on 2023-09-24 01:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
