name: Prodigal Spirit
cost: 2
grants: strong-spirit
description: |
  Some adherents are so accustomed to visiting the Spirit World that the transition of death is not quite so jarring an experience as it might be for others. Gain the Strong Spirit Perk as a Breed Advantage from the Character Options Chapter.
