name: Oath of Living Peace
description: |
  Common among the clerics, druids, and other peaceful folk of the world, the Oathbearers of Living Peace seek non-violence in all its forms, whether by word, deed, or thought. Understanding, compassion, and mercy are the stepping stones to a world in nascent perfection.

  **Chosen Accent**: Radiance

  **Patrons**: Kemis, Olfrin, Linred, The Worldsoul, The First Voice, Lightbearer, Worldmender

  - The Divine Hand must never attack the Living first or purposefully goad the enemy into armed conflict.
  - The Divine Hand must respect life in all its natural forms.
  - The Divine Hand must attempt to aid the dying and seek out nonviolent means to solve conflict.

  **Power**

  - The Divine Hand may expend a point of Divine Grace to call “By My Voice Heal One to Dying.”
