name: Oath of Martyrdom
description: |
  Death is but another path to the Martyrs, and one taken not lightly, but willingly when the time is right. The Oathbearers of the Martyr seek a glorious death in service to their Patron, but think them not reckless - just determined, with the certitude that death is not the end.

  **Chosen Accent**: Agony

  **Patrons**: Yaziri, Diavalla, The Phoenix, Leovitrius, Linred, Vaen, The Huntress, The Hound

  - The Divine Hand must be willing to martyr themselves in the name of their faith. To that end, any breach of their Religious Tenets is also a breach of their Oath of Martyrdom.
  - The Divine Hand must willingly volunteer when the call is put out for highly dangerous quests and other similar matters that aid the faith or community, regardless of chance of success.

  **Power**

  - The Divine Hand may expend a point of Divine Grace to sacrifice their own health for another. To do so, they roleplay laying their hands on the target character (but not touching the player), expend a point of Divine Grace and Sacrifice any number of Life Points, up to their current Life Points. If they do, the target Heals X by Radiance, where X is the amount of Life Points sacrificed.
  - The Divine Hand may expend a point of Divine Grace to Grant Life by Radiance with a Touch. If they do, however, they take a Death Final Effect.
