name: Oath of The Iron Tyrant
description: |
  The Iron Tyrant is master of themselves before master of others, but inevitable in both realms. Perfection is not only both a path and goal, but a necessity - all else shall be discarded and ground into the earth. These Oathbearers care not for the weasel words of failure and incompetence, seeking only the absolute best, and rejecting all else.

  **Chosen Accent**: Mind

  **Patrons**: Sodron, Leovitrius, The Argent Lady, The Void Wyrm

  - Never tolerate failure, especially your own.
  - Always strive for control by any means necessary.
  - Never be content to allow the incompetent, passive, or foolish to have control over you.
  - Always respect those above you, but replace them when they falter.

  **Power**

  - The Divine Hand may expend a point of Divine Grace to gain a lasting burst of strength. Until the character has completed a long rest, they may engage in feats of strength such as carrying people without being slowed, tossing massive objects, opening a portcullis, breaking down a door or wall, or anything else appropriate for the situation.
