name: Oath of The Revealed Truth
description: |
  Secrets inevitably only benefit the keeper of that information, and far more often than not, the wielder of that knowledge maintains a stranglehold on it with the intent to gather power. With the revelation of secrets, the populace is unbound from the tyranny of ignorance, and the nefarious plans of those with ill intent. Enter the Oathbearers of The Revealed Truth: the forefront of the battle against secrecy and ignorance.

  **Chosen Accent**: Mind
  **Patrons**: Voxus, Olfrin, Nicodeimus, Vaðnír, Cassandra

  - The Divine Hand must seek to uncover lost knowledge of the world around them, and prevent those secrets from being hoarded by those who might suppress them.
  - The Divine Hand may not knowingly lie about factual information, and must actively share knowledge with any who would ask, unless doing so would otherwise violate another Oath taken or breach a religious tenet. In such a case, the Divine Hand can simply say, “I cannot say.”

  **Power**

  - The Divine Hand may call out to their Patron, expending a Divine Grace to gain a use of Insight, per the Perk.
