name: Oath of Sole Domination
description: |
  Primacy. Inevitability. Dominion. These are the watchwords of the path of the Sole Domination. These Oathbearers brook no conversation nor compromise; they seek out a black and white binary: join us or oppose us, there is no in-between. Ardent in the extreme, these Oathbearers are the faith’s most outspoken, and often aggressive members, certain in their path, and fanatical in their faith.

  **Chosen Accent**: Fear

  **Patrons**: Leovitrius, Sodron, The Argent Lady, The Moon Beast, The First to Want

  - The Divine Hand must do their due diligence to induct new members into their chosen faith.
  - The Divine Hand must actively suppress other faiths, and otherwise halt their growth.

  **Power**

  - The Divine Hand may expend a point of Divine Grace to call “Short Dominate by Fear” with a melee weapon attack.
